### ISSUE TITLE
gcc 4.9.3 warnings.

### ISSUE THREAD

**Issue by Techwolf** [janoc/libndofdev#3]
make -j8 'CFLAGS=-march=native -O2 -pipe -ggdb' 
cc -march=native -O2 -pipe -ggdb   -c -o ndofdev.o ndofdev.c
ndofdev.c: In function ‘ndof_init_first’:
ndofdev.c:186:9: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
         write(spacenav_fd, &led_ev, sizeof(struct input_event));
         ^
ndofdev.c: In function ‘ndof_libcleanup’:
ndofdev.c:229:9: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
         write(spacenav_fd, &led_ev, sizeof(struct input_event));

**Comment by janoc** [comment]
Those warnings can be safely ignored, write() returns a number of bytes written or -1 on error. These two lines just turn the LED on/off, there is little point in trying to handle an obscure failure here. 

I think your warning settings are a little bit too pedantic/excessive.

**Comment by Techwolf** [comment]
The only flags I set are -j8 'CFLAGS=-march=native -O2 -pipe -ggdb'  the rest are gentoo and/or gcc defaults.

**Comment by Techwolf** [comment]
Please understand that i'me only pointing them out. I am not some SL user demanding stuff. LOL

**Comment by janoc** [comment]
No worries, I am not going to shoot the messenger here :)

I think the -Werror and the ueber pedantic warning settings are from the SL viewer's defaults. I can fix this warning, even though it is silly.

**Comment by janoc** [comment]
Try this version, that should fix both your problems.

**Comment by Techwolf** [comment]
Will do that later today. I just linked in v0.6 and discover my spacenav doesn't work. Will be opening an issue once I figure out what went wrong.

**Comment by janoc** [comment]
Okay, keep me posted. Most often it is a problem with permissions to the /dev/input/xxx devices.
